name: duffing_double_well_2d
dimension: 2

boundaries:
  source:
    kind: dataset
    name: diagonal_gaussian
    parameters:
      mean: [-1.0, 0.0]
      std: 0.1
    sample_noise: 0.0
  target:
    kind: dataset
    name: diagonal_gaussian
    parameters:
      mean: [1.0, 0.0]
      std: 0.1
    sample_noise: 0.0

functional:
  linear:
    name: duffing_double_well_2d
    coefficient: 1.0
    parameters:
      kappa: 5.0
  internal: null
  interaction: null
evaluation:
  num_samples: 3000
  max_metric_samples: 512
  num_sliced_projections: 128
  mmd_bandwidth: null
  plot_trajectory_count: 512
  plot_dir1: 0
  plot_dir2: 1
