"""Potential classes for Hamiltonian flow matching."""

from .configured_potential import ConfiguredPotential
from .interaction_potentials import (
    InteractionKernel,
    InteractionPotential,
    KernelInteractionPotential,
    RationalQuadraticInteractionKernel,
    RepulsiveKernel,
    build_interaction_potential,
)
from .internal_potentials import EntropyPotential, InternalPotential, build_internal_potential
from .linear_potentials import (
    CrowdNavObstaclePotential,
    DoubleWellPotential,
    DuffingDoubleWellPotential,
    HarmonicPotential,
    HillPotential,
    FixedCenterThreeBodyPotential,
    GridSpringPotential,
    LinearPotential,
    ObstaclePotential,
    SmoothCoulombPotential,
    build_linear_potential,
    node_index,
    crowd_nav_obstacle_grad,
    crowd_nav_obstacle_v,
    double_well_grad,
    double_well_v,
    harmonic_grad,
    harmonic_v,
    hill_grad,
    hill_v,
    obstacle_grad,
    obstacle_v,
    von_neumann_edges,
    von_neumann_grid_laplacian,
)
from .potentials import Potential
from .schedules import SigmaSchedule

__all__ = [
    "Potential",
    "LinearPotential",
    "InternalPotential",
    "InteractionPotential",
    "InteractionKernel",
    "SigmaSchedule",
    "ConfiguredPotential",
    "ObstaclePotential",
    "SmoothCoulombPotential",
    "HarmonicPotential",
    "DoubleWellPotential",
    "HillPotential",
    "FixedCenterThreeBodyPotential",
    "GridSpringPotential",
    "CrowdNavObstaclePotential",
    "EntropyPotential",
    "KernelInteractionPotential",
    "RationalQuadraticInteractionKernel",
    "RepulsiveKernel",
    "harmonic_v",
    "harmonic_grad",
    "double_well_v",
    "double_well_grad",
    "hill_v",
    "hill_grad",
    "obstacle_v",
    "obstacle_grad",
    "crowd_nav_obstacle_v",
    "crowd_nav_obstacle_grad",
    "build_linear_potential",
    "node_index",
    "build_internal_potential",
    "von_neumann_edges",
    "von_neumann_grid_laplacian",
    "build_interaction_potential",
]
